name: Build and Deploy

on:
  push:
    branches: [master]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Token_Hggnface
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      - name: Replace token placeholder
        run: |
          echo "Checking secrets..."
          echo "Secret value: ${{ secrets.TOKEN_HUGGINGFCE }}"
          echo "Token length: ${#secrets.TOKEN_HUGGINGFCE}"
          sed -i 's/HF_TOKEN_PLACEHOLDER/'"${{ secrets.TOKEN_HUGGINGFCE }}"'/g' script.js
          echo "Replacement done"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
